### ISSUE TITLE
No anda la descarga por Bittorrent

### ISSUE THREAD

**Issue by lobit0** [piratas-ar/utopia.partidopirata.com.ar#14]
Hace mil que la tengo bajando y nunca pasó nada :<

Probé bajar algunos archivos por HTTP, meterlos en la carpeta de la descarga y forzar una verificación: alguno lo agarró al 100% y a otro parcialmente... pero a la mayoría no.

Si alguien lo tiene entero, que lo siembre.

**Comment by fauno** [comment]
eeeh fijate ahora a ver

**Comment by fauno** [comment]
me tiró un error el tracker, fijate con http://tracker.publicbt.com

**Comment by fauno** [comment]
tampoco... que trackers publicos estan andando?

**Comment by lobit0** [comment]
Ahi se bajó todo :D comparto
